# requires:
# - oraclejdk
# - elasticsearch
# - nginx
---

- name: kibana | Ensure app apt dependencies are installed
  apt: pkg={{ item }} state=installed
  with_items:
    - python-software-properties
    - git
    - nginx

- name: kibana | Ensure {{ kibana_app_dir }} exists
  file: path={{ kibana_app_dir }} state=directory owner=root group=root mode=0755

- name: kibana | Ensure subdirectories exist
  file: path={{ kibana_app_dir }}/{{ item }} owner=root group=root mode=0755 state=directory
  with_items:
    - htdocs
    - share

- name: kibana | ensure we have the specified kibana release
  get_url: url={{ kibana_url }} dest={{ kibana_app_dir }}/share/{{ kibana_file }}

- name: kibana | extract
  shell: >
    chdir={{ kibana_app_dir }}/share
    tar -xzvf {{ kibana_app_dir }}/share/{{ kibana_file }}
    creates={{ kibana_app_dir }}/share/{{ kibana_file|replace('.tar.gz','') }}

- name: kibana | install
  shell: >
    chdir={{ kibana_app_dir }}/share/{{ kibana_file|replace('.tar.gz','') }}
    cp -R * {{ kibana_app_dir }}/htdocs/

- name: kibana | copy config
  template: src=config.js.j2 dest={{ kibana_app_dir }}/htdocs/config.js
